// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ysjlqvlxfpwhuegcxbrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlzamxxdmx4ZnB3aHVlZ2N4YnJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MDAzOTMsImV4cCI6MjA2Mjk3NjM5M30.LP4TUhL-1Ip7iqG4pYKnMZDTShI072RfhEPfhZglT8M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);